"""
Composições de serviço para instalação de ar-condicionado Split.
Cada composição agrupa materiais, mão de obra e ferramentas.

Formato:
- codigo: Identificador único
- descricao: Descrição curta
- desc_pre: Texto antes da variável (opcional)
- desc_pos: Texto após a variável (opcional)
- unid_sing: Unidade variável singular (opcional, ex: "metro")
- unid_plur: Unidade variável plural (opcional, ex: "metros")
- itens: Lista de (Tipo, Código, Qtd_Base, Qtd_por_Metro)
"""

COMPOSICOES = [
    {
        'codigo': 'COMP_INST_9K',
        'descricao': 'Instalação Split Hi-Wall 9.000 BTUs',
        'desc_pre': 'Instalação Split 9.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_14_FLEX', 0, 1.1),
            ('MAT', 'TUB_38_FLEX', 0, 1.1),
            ('MAT', 'ISO_14_ELA_E9', 0, 1.1),
            ('MAT', 'ISO_38_ELA_E9', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.15, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'DRN_CRIS_34', 0, 1.1),
            ('MAT', 'SUP_EVAP', 1, 0),
            ('MAT', 'SUP_BUCHA', 6, 0),
            ('MAT', 'SUP_CHIP', 6, 0),
            ('MAT', 'ACA_ESPUMA', 0.3, 0),
            ('MAT', 'ACA_FITA_ISO', 0.25, 0),
            ('MAT', 'ACA_FITA_AUT', 0.2, 0),
            ('MAT', 'SOL_PRATA', 2, 0),
            ('MAT', 'SOL_FLUXO', 0.2, 0),
            ('MO', 'MO_TEC', 2, 0.15),
            ('MO', 'MO_AJU', 2, 0.15),
            ('FER', 'FER_VACUO', 0.5, 0),
            ('FER', 'FER_MANIF', 0.5, 0),
            ('FER', 'FER_SOLDA', 0.5, 0),
            ('FER', 'FER_MANUAL', 2.5, 0),
        ]
    },
    {
        'codigo': 'COMP_SUP_MF',
        'descricao': 'Adicional suporte mão francesa 400mm (condensadora)',
        'itens': [
            ('MAT', 'SUP_MF_400', 1, 0),
            ('MAT', 'SUP_PARF_100', 4, 0),
            ('MO', 'MO_TEC', 0.75, 0),
            ('MO', 'MO_AJU', 0.75, 0),
            ('FER', 'FER_PERF', 0.5, 0),
        ]
    },
    {
        'codigo': 'COMP_SUP_CALCO',
        'descricao': 'Adicional calços de borracha (condensadora)',
        'itens': [
            ('MAT', 'SUP_CALCO', 1, 0),
            ('MO', 'MO_TEC', 0.25, 0),
        ]
    },
    {
        'codigo': 'COMP_ELE',
        'descricao': 'Alimentação elétrica 220V monofásica',
        'desc_pre': 'Alimentação elétrica 220V mono com ',
        'desc_pos': ' de cabo e eletroduto',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'CAB_PP_25', 0, 1.1),
            ('MAT', 'COND_CORR_34', 0, 1.1),
            ('MAT', 'COND_CURV_34', 2, 0),
            ('MAT', 'COND_ABRC_34', 0, 1.2),
            ('MAT', 'ACA_FITA_ISO', 0.25, 0),
            ('MO', 'MO_ELE', 1, 0.15),
            ('FER', 'FER_MULT', 0.5, 0),
        ]
    },

    {
        'codigo': 'COMP_ELE_9_12K',
        'descricao': 'Alimentação elétrica 220V monofásica 9-12K',
        'desc_pre': 'Alimentação elétrica 220V monofásica 9-12K com ',
        'desc_pos': ' de cabo e eletroduto',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'CAB_PP_15', 0, 1.1),
            ('MAT', 'COND_CORR_34', 0, 1.1),
            ('MAT', 'COND_CURV_34', 2, 0),
            ('MAT', 'COND_ABRC_34', 0, 1.2),
            ('MAT', 'DISJ_M_16', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.25, 0),
            ('MO', 'MO_ELE', 1, 0.12),
            ('FER', 'FER_MULT', 0.5, 0),
        ]
    },
    {
        'codigo': 'COMP_ELE_18_24K',
        'descricao': 'Alimentação elétrica 220V monofásica 18-24K',
        'desc_pre': 'Alimentação elétrica 220V monofásica 18-24K com ',
        'desc_pos': ' de cabo e eletroduto',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'CAB_PP_25', 0, 1.1),
            ('MAT', 'COND_CORR_34', 0, 1.1),
            ('MAT', 'COND_CURV_34', 2, 0),
            ('MAT', 'COND_ABRC_34', 0, 1.2),
            ('MAT', 'DISJ_B_20', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.25, 0),
            ('MO', 'MO_ELE', 1.25, 0.15),
            ('FER', 'FER_MULT', 0.5, 0),
        ]
    },
    {
        'codigo': 'COMP_ELE_30_36K',
        'descricao': 'Alimentação elétrica 220V monofásica 30-36K',
        'desc_pre': 'Alimentação elétrica 220V monofásica 30-36K com ',
        'desc_pos': ' de cabo e eletroduto',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'CAB_PP_40', 0, 1.1),
            ('MAT', 'COND_CORR_34', 0, 1.1),
            ('MAT', 'COND_CURV_34', 2, 0),
            ('MAT', 'COND_ABRC_34', 0, 1.2),
            ('MAT', 'DISJ_B_32', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.3, 0),
            ('MO', 'MO_ELE', 1.5, 0.2),
            ('FER', 'FER_MULT', 0.75, 0),
        ]
    },
    {
        'codigo': 'COMP_ELE_48_60K',
        'descricao': 'Alimentação elétrica 220V monofásica 48-60K',
        'desc_pre': 'Alimentação elétrica 220V monofásica 48-60K com ',
        'desc_pos': ' de cabo e eletroduto',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'CAB_PP_60', 0, 1.1),
            ('MAT', 'COND_CORR_100', 0, 1.1),
            ('MAT', 'COND_CURV_34', 2, 0),
            ('MAT', 'COND_ABRC_34', 0, 1.2),
            ('MAT', 'DISJ_B_40', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.3, 0),
            ('MO', 'MO_ELE', 1.75, 0.25),
            ('FER', 'FER_MULT', 1, 0),
        ]
    },

    {
        'codigo': 'COMP_DRN_CRIS',
        'descricao': 'Dreno mangueira cristal',
        'desc_pre': 'Dreno mangueira cristal com ',
        'desc_pos': '',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'DRN_CRIS_34', 0, 1.1),
            ('MAT', 'DRN_ABRC', 0, 1.3),
            ('MO', 'MO_TEC', 0.25, 0.1),
        ]
    },
    {
        'codigo': 'COMP_DRN_PVC',
        'descricao': 'Dreno tubo PVC 25mm',
        'desc_pre': 'Dreno tubo PVC 25mm com ',
        'desc_pos': '',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'DRN_PVC_25', 0, 1.1),
            ('MAT', 'DRN_CURV_25', 2, 0),
            ('MAT', 'DRN_LUVA_25', 0, 0.5),
            ('MAT', 'DRN_COLA', 0.3, 0),
            ('MO', 'MO_TEC', 0.5, 0.15),
        ]
    },
    {
        'codigo': 'COMP_FURO',
        'descricao': 'Furo em parede/laje/viga (até 20cm espessura)',
        'itens': [
            ('MAT', 'ACA_ESPUMA', 0.2, 0),
            ('MAT', 'ACA_MASSA', 0.3, 0),
            ('MO', 'MO_TEC', 0.75, 0),
            ('MO', 'MO_AJU', 0.75, 0),
            ('FER', 'FER_PERF', 0.5, 0),
            ('FER', 'FER_SERRA_65', 1, 0),
        ]
    },
    {
        'codigo': 'COMP_CAN_50',
        'descricao': 'Acabamento canaleta PVC 50mm',
        'desc_pre': 'Acabamento canaleta PVC 50mm com ',
        'desc_pos': '',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'ACA_CAN_50', 0, 1.1),
            ('MAT', 'SUP_BUCHA', 0, 2),
            ('MAT', 'SUP_CHIP', 0, 2),
            ('MO', 'MO_TEC', 0, 0.25),
        ]
    },
    {
        'codigo': 'COMP_ALV',
        'descricao': 'Abertura e fechamento alvenaria',
        'desc_pre': 'Abertura e fechamento alvenaria com ',
        'desc_pos': ' para embutir linha',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'ALV_ARG', 0, 0.5),
            ('MAT', 'ALV_TIJ', 0, 10),
            ('MO', 'MO_PED', 1, 1.25),
            ('MO', 'MO_SERV', 1, 1.25),
            ('FER', 'FER_MANUAL', 1, 1),
        ]
    },
    {
        'codigo': 'COMP_FACH',
        'descricao': 'Instalação condensadora em fachada (com suporte)',
        'itens': [
            ('MAT', 'SUP_MF_500', 1, 0),
            ('MAT', 'SUP_PARF_150', 4, 0),
            ('MO', 'MO_TEC', 2, 0),
            ('MO', 'MO_AJU', 2, 0),
            ('MO', 'MO_FAC', 2, 0),
            ('FER', 'FER_PERF', 1, 0),
            ('FER', 'FER_MANUAL', 2, 0),
        ]
    },
    {
        'codigo': 'COMP_ALT',
        'descricao': 'Adicional trabalho em altura (acima 3m)',
        'itens': [
            ('MO', 'MO_ALT', 2, 0),
            ('FER', 'FER_ESCADA', 2, 0),
        ]
    },
    {
        'codigo': 'COMP_BOMB_DRN',
        'descricao': 'Instalação bomba de dreno',
        'itens': [
            ('EQP', 'EQP_BOMB_P', 1, 0),
            ('MAT', 'DRN_CRIS_34', 2, 0),
            ('MAT', 'ACA_FITA_ISO', 0.1, 0),
            ('MO', 'MO_TEC', 1, 0),
        ]
    },
    {
        'codigo': 'COMP_DISJ',
        'descricao': 'Instalação disjuntor no QDC',
        'itens': [
            ('MAT', 'DISJ_M_16', 1, 0),
            ('MAT', 'CAB_FLEX_25', 3, 0),
            ('MAT', 'ACA_FITA_ISO', 0.15, 0),
            ('MO', 'MO_ELE', 1, 0),
            ('FER', 'FER_MULT', 0.25, 0),
        ]
    },
    {
        'codigo': 'COMP_DRN_ESG',
        'descricao': 'Conexão dreno em rede esgoto (com sifão)',
        'itens': [
            ('MAT', 'DRN_PVC_25', 1, 0),
            ('MAT', 'DRN_SIFAO', 1, 0),
            ('MAT', 'DRN_CURV_25', 1, 0),
            ('MAT', 'DRN_COLA', 0.2, 0),
            ('MO', 'MO_TEC', 0.75, 0),
        ]
    },
    {
        'codigo': 'COMP_DESINST',
        'descricao': 'Desinstalação de equipamento Split',
        'itens': [
            ('MO', 'MO_TEC', 1.5, 0),
            ('MO', 'MO_AJU', 1.5, 0),
            ('FER', 'FER_MANIF', 0.5, 0),
            ('FER', 'FER_MANUAL', 1.5, 0),
        ]
    },
    {
        'codigo': 'COMP_GAS_ADIC',
        'descricao': 'Carga adicional gás R-410A (por kg)',
        'itens': [
            ('MAT', 'GAS_R410A', 1, 0),
            ('MO', 'MO_TEC', 0.5, 0),
            ('FER', 'FER_MANIF', 0.25, 0),
            ('FER', 'FER_BAL', 0.25, 0),
        ]
    },
    # ========== INSTALAÇÕES HIGH WALL ==========
    {
        'codigo': 'COMP_INST_HW_12K',
        'descricao': 'Instalação Split Hi-Wall 12.000 BTUs',
        'desc_pre': 'Instalação Split Hi-Wall 12.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_14_FLEX', 0, 1.1),
            ('MAT', 'TUB_38_FLEX', 0, 1.1),
            ('MAT', 'ISO_14_ELA_E9', 0, 1.1),
            ('MAT', 'ISO_38_ELA_E9', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.15, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'DRN_CRIS_34', 0, 1.1),
            ('MAT', 'SUP_EVAP', 1, 0),
            ('MAT', 'SUP_BUCHA', 6, 0),
            ('MAT', 'SUP_CHIP', 6, 0),
            ('MAT', 'ACA_ESPUMA', 0.3, 0),
            ('MAT', 'ACA_FITA_ISO', 0.25, 0),
            ('MAT', 'ACA_FITA_AUT', 0.2, 0),
            ('MAT', 'SOL_PRATA', 2, 0),
            ('MAT', 'SOL_FLUXO', 0.2, 0),
            ('MO', 'MO_TEC', 2.5, 0.15),
            ('MO', 'MO_AJU', 2.5, 0.15),
            ('FER', 'FER_VACUO', 0.5, 0),
            ('FER', 'FER_MANIF', 0.5, 0),
            ('FER', 'FER_SOLDA', 0.5, 0),
            ('FER', 'FER_MANUAL', 3, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_HW_18K',
        'descricao': 'Instalação Split Hi-Wall 18.000 BTUs',
        'desc_pre': 'Instalação Split Hi-Wall 18.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_14_FLEX', 0, 1.1),
            ('MAT', 'TUB_12_FLEX', 0, 1.1),
            ('MAT', 'ISO_14_ELA_E9', 0, 1.1),
            ('MAT', 'ISO_12_ELA_E13', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.2, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'DRN_CRIS_34', 0, 1.1),
            ('MAT', 'SUP_EVAP', 1, 0),
            ('MAT', 'SUP_BUCHA', 8, 0),
            ('MAT', 'SUP_CHIP', 8, 0),
            ('MAT', 'ACA_ESPUMA', 0.4, 0),
            ('MAT', 'ACA_FITA_ISO', 0.3, 0),
            ('MAT', 'ACA_FITA_AUT', 0.25, 0),
            ('MAT', 'SOL_PRATA', 2, 0),
            ('MAT', 'SOL_FLUXO', 0.2, 0),
            ('MO', 'MO_TEC', 3, 0.2),
            ('MO', 'MO_AJU', 3, 0.2),
            ('FER', 'FER_VACUO', 0.75, 0),
            ('FER', 'FER_MANIF', 0.75, 0),
            ('FER', 'FER_SOLDA', 0.75, 0),
            ('FER', 'FER_MANUAL', 3.5, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_HW_22K',
        'descricao': 'Instalação Split Hi-Wall 22.000 BTUs',
        'desc_pre': 'Instalação Split Hi-Wall 22.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_14_FLEX', 0, 1.1),
            ('MAT', 'TUB_12_FLEX', 0, 1.1),
            ('MAT', 'ISO_14_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_12_ELA_E13', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.25, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'DRN_CRIS_34', 0, 1.1),
            ('MAT', 'SUP_EVAP', 1, 0),
            ('MAT', 'SUP_BUCHA', 8, 0),
            ('MAT', 'SUP_CHIP', 8, 0),
            ('MAT', 'ACA_ESPUMA', 0.4, 0),
            ('MAT', 'ACA_FITA_ISO', 0.3, 0),
            ('MAT', 'ACA_FITA_AUT', 0.25, 0),
            ('MAT', 'SOL_PRATA', 3, 0),
            ('MAT', 'SOL_FLUXO', 0.3, 0),
            ('MO', 'MO_TEC', 3.5, 0.2),
            ('MO', 'MO_AJU', 3.5, 0.2),
            ('FER', 'FER_VACUO', 0.75, 0),
            ('FER', 'FER_MANIF', 0.75, 0),
            ('FER', 'FER_SOLDA', 0.75, 0),
            ('FER', 'FER_MANUAL', 4, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_HW_24K',
        'descricao': 'Instalação Split Hi-Wall 24.000 BTUs',
        'desc_pre': 'Instalação Split Hi-Wall 24.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_14_FLEX', 0, 1.1),
            ('MAT', 'TUB_12_FLEX', 0, 1.1),
            ('MAT', 'ISO_14_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_12_ELA_E13', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.25, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'DRN_CRIS_34', 0, 1.1),
            ('MAT', 'SUP_EVAP', 1, 0),
            ('MAT', 'SUP_BUCHA', 8, 0),
            ('MAT', 'SUP_CHIP', 8, 0),
            ('MAT', 'ACA_ESPUMA', 0.4, 0),
            ('MAT', 'ACA_FITA_ISO', 0.3, 0),
            ('MAT', 'ACA_FITA_AUT', 0.25, 0),
            ('MAT', 'SOL_PRATA', 3, 0),
            ('MAT', 'SOL_FLUXO', 0.3, 0),
            ('MO', 'MO_TEC', 3.5, 0.2),
            ('MO', 'MO_AJU', 3.5, 0.2),
            ('FER', 'FER_VACUO', 0.75, 0),
            ('FER', 'FER_MANIF', 0.75, 0),
            ('FER', 'FER_SOLDA', 0.75, 0),
            ('FER', 'FER_MANUAL', 4, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_HW_30K',
        'descricao': 'Instalação Split Hi-Wall 30.000 BTUs',
        'desc_pre': 'Instalação Split Hi-Wall 30.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_38_FLEX', 0, 1.1),
            ('MAT', 'TUB_58_FLEX', 0, 1.1),
            ('MAT', 'ISO_38_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_58_ELA_E19', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.3, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'DRN_CRIS_34', 0, 1.1),
            ('MAT', 'SUP_EVAP', 1, 0),
            ('MAT', 'SUP_BUCHA', 10, 0),
            ('MAT', 'SUP_CHIP', 10, 0),
            ('MAT', 'ACA_ESPUMA', 0.5, 0),
            ('MAT', 'ACA_FITA_ISO', 0.4, 0),
            ('MAT', 'ACA_FITA_AUT', 0.3, 0),
            ('MAT', 'SOL_PRATA', 3, 0),
            ('MAT', 'SOL_FLUXO', 0.3, 0),
            ('MO', 'MO_TEC', 4, 0.25),
            ('MO', 'MO_AJU', 4, 0.25),
            ('FER', 'FER_VACUO', 1, 0),
            ('FER', 'FER_MANIF', 1, 0),
            ('FER', 'FER_SOLDA', 1, 0),
            ('FER', 'FER_MANUAL', 4.5, 0),
        ]
    },

    {
        'codigo': 'COMP_INST_HW_36K',
        'descricao': 'Instalação Split Hi-Wall 36.000 BTUs',
        'desc_pre': 'Instalação Split Hi-Wall 36.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_38_FLEX', 0, 1.1),
            ('MAT', 'TUB_58_FLEX', 0, 1.1),
            ('MAT', 'ISO_38_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_58_ELA_E19', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.35, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'DRN_CRIS_34', 0, 1.1),
            ('MAT', 'SUP_EVAP', 1, 0),
            ('MAT', 'SUP_BUCHA', 10, 0),
            ('MAT', 'SUP_CHIP', 10, 0),
            ('MAT', 'ACA_ESPUMA', 0.5, 0),
            ('MAT', 'ACA_FITA_ISO', 0.4, 0),
            ('MAT', 'ACA_FITA_AUT', 0.3, 0),
            ('MAT', 'SOL_PRATA', 3.5, 0),
            ('MAT', 'SOL_FLUXO', 0.35, 0),
            ('MO', 'MO_TEC', 4.5, 0.3),
            ('MO', 'MO_AJU', 4.5, 0.3),
            ('FER', 'FER_VACUO', 1, 0),
            ('FER', 'FER_MANIF', 1, 0),
            ('FER', 'FER_SOLDA', 1, 0),
            ('FER', 'FER_MANUAL', 5, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_HW_48K',
        'descricao': 'Instalação Split Hi-Wall 48.000 BTUs',
        'desc_pre': 'Instalação Split Hi-Wall 48.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_38_FLEX', 0, 1.1),
            ('MAT', 'TUB_58_FLEX', 0, 1.1),
            ('MAT', 'ISO_38_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_58_ELA_E19', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.45, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'DRN_CRIS_34', 0, 1.1),
            ('MAT', 'SUP_EVAP', 1, 0),
            ('MAT', 'SUP_BUCHA', 12, 0),
            ('MAT', 'SUP_CHIP', 12, 0),
            ('MAT', 'ACA_ESPUMA', 0.6, 0),
            ('MAT', 'ACA_FITA_ISO', 0.45, 0),
            ('MAT', 'ACA_FITA_AUT', 0.35, 0),
            ('MAT', 'SOL_PRATA', 4, 0),
            ('MAT', 'SOL_FLUXO', 0.4, 0),
            ('MO', 'MO_TEC', 5.5, 0.35),
            ('MO', 'MO_AJU', 5.5, 0.35),
            ('FER', 'FER_VACUO', 1.25, 0),
            ('FER', 'FER_MANIF', 1.25, 0),
            ('FER', 'FER_SOLDA', 1.25, 0),
            ('FER', 'FER_MANUAL', 6, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_HW_60K',
        'descricao': 'Instalação Split Hi-Wall 60.000 BTUs',
        'desc_pre': 'Instalação Split Hi-Wall 60.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_38_FLEX', 0, 1.1),
            ('MAT', 'TUB_34_FLEX', 0, 1.1),
            ('MAT', 'ISO_38_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_34_ELA_E19', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.5, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'DRN_CRIS_34', 0, 1.1),
            ('MAT', 'SUP_EVAP', 1, 0),
            ('MAT', 'SUP_BUCHA', 12, 0),
            ('MAT', 'SUP_CHIP', 12, 0),
            ('MAT', 'ACA_ESPUMA', 0.7, 0),
            ('MAT', 'ACA_FITA_ISO', 0.5, 0),
            ('MAT', 'ACA_FITA_AUT', 0.4, 0),
            ('MAT', 'SOL_PRATA', 4.5, 0),
            ('MAT', 'SOL_FLUXO', 0.45, 0),
            ('MO', 'MO_TEC', 6, 0.4),
            ('MO', 'MO_AJU', 6, 0.4),
            ('FER', 'FER_VACUO', 1.5, 0),
            ('FER', 'FER_MANIF', 1.5, 0),
            ('FER', 'FER_SOLDA', 1.5, 0),
            ('FER', 'FER_MANUAL', 6.5, 0),
        ]
    },

    # ========== INSTALAÇÕES CASSETE 4 VIAS ==========
    {
        'codigo': 'COMP_INST_CS4_18K',
        'descricao': 'Instalação Split Cassete 4 Vias 18.000 BTUs',
        'desc_pre': 'Instalação Split Cassete 4 Vias 18.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_14_FLEX', 0, 1.1),
            ('MAT', 'TUB_12_FLEX', 0, 1.1),
            ('MAT', 'ISO_14_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_12_ELA_E13', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.25, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'CS_PAINEL_60', 1, 0),
            ('MAT', 'CS_GRELHA_RET', 1, 0),
            ('MAT', 'CS_SUSP_VARET', 1, 0),
            ('MAT', 'CS_DRENO_BOMB', 1, 0),
            ('MAT', 'DRN_CRIS_34', 3, 0),
            ('MAT', 'ACA_ESPUMA', 0.3, 0),
            ('MAT', 'ACA_FITA_ISO', 0.3, 0),
            ('MAT', 'SOL_PRATA', 2, 0),
            ('MAT', 'SOL_FLUXO', 0.2, 0),
            ('MO', 'MO_TEC', 4, 0.2),
            ('MO', 'MO_AJU', 4, 0.2),
            ('FER', 'FER_VACUO', 0.75, 0),
            ('FER', 'FER_MANIF', 0.75, 0),
            ('FER', 'FER_SOLDA', 0.75, 0),
            ('FER', 'FER_MANUAL', 4, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_CS4_24K',
        'descricao': 'Instalação Split Cassete 4 Vias 24.000 BTUs',
        'desc_pre': 'Instalação Split Cassete 4 Vias 24.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_14_FLEX', 0, 1.1),
            ('MAT', 'TUB_12_FLEX', 0, 1.1),
            ('MAT', 'ISO_14_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_12_ELA_E13', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.3, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'CS_PAINEL_60', 1, 0),
            ('MAT', 'CS_GRELHA_RET', 1, 0),
            ('MAT', 'CS_SUSP_VARET', 1, 0),
            ('MAT', 'CS_DRENO_BOMB', 1, 0),
            ('MAT', 'DRN_CRIS_34', 3, 0),
            ('MAT', 'ACA_ESPUMA', 0.3, 0),
            ('MAT', 'ACA_FITA_ISO', 0.3, 0),
            ('MAT', 'SOL_PRATA', 3, 0),
            ('MAT', 'SOL_FLUXO', 0.3, 0),
            ('MO', 'MO_TEC', 4.5, 0.25),
            ('MO', 'MO_AJU', 4.5, 0.25),
            ('FER', 'FER_VACUO', 0.75, 0),
            ('FER', 'FER_MANIF', 0.75, 0),
            ('FER', 'FER_SOLDA', 0.75, 0),
            ('FER', 'FER_MANUAL', 4.5, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_CS4_36K',
        'descricao': 'Instalação Split Cassete 4 Vias 36.000 BTUs',
        'desc_pre': 'Instalação Split Cassete 4 Vias 36.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_38_FLEX', 0, 1.1),
            ('MAT', 'TUB_58_FLEX', 0, 1.1),
            ('MAT', 'ISO_38_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_58_ELA_E19', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.35, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'CS_PAINEL_90', 1, 0),
            ('MAT', 'CS_GRELHA_RET', 1, 0),
            ('MAT', 'CS_SUSP_VARET', 1, 0),
            ('MAT', 'CS_DRENO_BOMB', 1, 0),
            ('MAT', 'DRN_CRIS_100', 3, 0),
            ('MAT', 'ACA_ESPUMA', 0.4, 0),
            ('MAT', 'ACA_FITA_ISO', 0.4, 0),
            ('MAT', 'SOL_PRATA', 3, 0),
            ('MAT', 'SOL_FLUXO', 0.3, 0),
            ('MO', 'MO_TEC', 5, 0.3),
            ('MO', 'MO_AJU', 5, 0.3),
            ('FER', 'FER_VACUO', 1, 0),
            ('FER', 'FER_MANIF', 1, 0),
            ('FER', 'FER_SOLDA', 1, 0),
            ('FER', 'FER_MANUAL', 5, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_CS4_48K',
        'descricao': 'Instalação Split Cassete 4 Vias 48.000 BTUs',
        'desc_pre': 'Instalação Split Cassete 4 Vias 48.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_38_FLEX', 0, 1.1),
            ('MAT', 'TUB_58_FLEX', 0, 1.1),
            ('MAT', 'ISO_38_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_58_ELA_E19', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.4, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'CS_PAINEL_90', 1, 0),
            ('MAT', 'CS_GRELHA_RET', 1, 0),
            ('MAT', 'CS_SUSP_VARET', 1, 0),
            ('MAT', 'CS_DRENO_BOMB', 1, 0),
            ('MAT', 'DRN_CRIS_100', 3, 0),
            ('MAT', 'ACA_ESPUMA', 0.5, 0),
            ('MAT', 'ACA_FITA_ISO', 0.5, 0),
            ('MAT', 'SOL_PRATA', 4, 0),
            ('MAT', 'SOL_FLUXO', 0.4, 0),
            ('MO', 'MO_TEC', 6, 0.35),
            ('MO', 'MO_AJU', 6, 0.35),
            ('FER', 'FER_VACUO', 1.25, 0),
            ('FER', 'FER_MANIF', 1.25, 0),
            ('FER', 'FER_SOLDA', 1.25, 0),
            ('FER', 'FER_MANUAL', 6, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_CS4_60K',
        'descricao': 'Instalação Split Cassete 4 Vias 60.000 BTUs',
        'desc_pre': 'Instalação Split Cassete 4 Vias 60.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_38_FLEX', 0, 1.1),
            ('MAT', 'TUB_34_FLEX', 0, 1.1),
            ('MAT', 'ISO_38_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_34_ELA_E19', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.5, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'CS_PAINEL_120', 1, 0),
            ('MAT', 'CS_GRELHA_RET', 1, 0),
            ('MAT', 'CS_SUSP_VARET', 1, 0),
            ('MAT', 'CS_DRENO_BOMB', 1, 0),
            ('MAT', 'DRN_CRIS_100', 4, 0),
            ('MAT', 'ACA_ESPUMA', 0.6, 0),
            ('MAT', 'ACA_FITA_ISO', 0.6, 0),
            ('MAT', 'SOL_PRATA', 4, 0),
            ('MAT', 'SOL_FLUXO', 0.4, 0),
            ('MO', 'MO_TEC', 7, 0.4),
            ('MO', 'MO_AJU', 7, 0.4),
            ('FER', 'FER_VACUO', 1.5, 0),
            ('FER', 'FER_MANIF', 1.5, 0),
            ('FER', 'FER_SOLDA', 1.5, 0),
            ('FER', 'FER_MANUAL', 7, 0),
        ]
    },
    # ========== INSTALAÇÕES PISO-TETO ==========
    {
        'codigo': 'COMP_INST_PT_18K',
        'descricao': 'Instalação Split Piso-Teto 18.000 BTUs',
        'desc_pre': 'Instalação Split Piso-Teto 18.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_14_FLEX', 0, 1.1),
            ('MAT', 'TUB_12_FLEX', 0, 1.1),
            ('MAT', 'ISO_14_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_12_ELA_E13', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.25, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'SUP_MF_500', 1, 0),
            ('MAT', 'SUP_PARF_150', 4, 0),
            ('MAT', 'DRN_CRIS_34', 2, 0),
            ('MAT', 'ACA_ESPUMA', 0.3, 0),
            ('MAT', 'ACA_FITA_ISO', 0.3, 0),
            ('MAT', 'SOL_PRATA', 2, 0),
            ('MAT', 'SOL_FLUXO', 0.2, 0),
            ('MO', 'MO_TEC', 3.5, 0.2),
            ('MO', 'MO_AJU', 3.5, 0.2),
            ('FER', 'FER_VACUO', 0.75, 0),
            ('FER', 'FER_MANIF', 0.75, 0),
            ('FER', 'FER_SOLDA', 0.75, 0),
            ('FER', 'FER_MANUAL', 4, 0),
            ('FER', 'FER_PERF', 0.5, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_PT_24K',
        'descricao': 'Instalação Split Piso-Teto 24.000 BTUs',
        'desc_pre': 'Instalação Split Piso-Teto 24.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_14_FLEX', 0, 1.1),
            ('MAT', 'TUB_12_FLEX', 0, 1.1),
            ('MAT', 'ISO_14_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_12_ELA_E13', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.3, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'SUP_MF_500', 1, 0),
            ('MAT', 'SUP_PARF_150', 4, 0),
            ('MAT', 'DRN_CRIS_34', 2, 0),
            ('MAT', 'ACA_ESPUMA', 0.3, 0),
            ('MAT', 'ACA_FITA_ISO', 0.3, 0),
            ('MAT', 'SOL_PRATA', 3, 0),
            ('MAT', 'SOL_FLUXO', 0.3, 0),
            ('MO', 'MO_TEC', 4, 0.25),
            ('MO', 'MO_AJU', 4, 0.25),
            ('FER', 'FER_VACUO', 0.75, 0),
            ('FER', 'FER_MANIF', 0.75, 0),
            ('FER', 'FER_SOLDA', 0.75, 0),
            ('FER', 'FER_MANUAL', 4.5, 0),
            ('FER', 'FER_PERF', 0.5, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_PT_36K',
        'descricao': 'Instalação Split Piso-Teto 36.000 BTUs',
        'desc_pre': 'Instalação Split Piso-Teto 36.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_38_FLEX', 0, 1.1),
            ('MAT', 'TUB_58_FLEX', 0, 1.1),
            ('MAT', 'ISO_38_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_58_ELA_E19', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.35, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'SUP_MF_600', 1, 0),
            ('MAT', 'SUP_PARF_150', 4, 0),
            ('MAT', 'DRN_CRIS_100', 2, 0),
            ('MAT', 'ACA_ESPUMA', 0.4, 0),
            ('MAT', 'ACA_FITA_ISO', 0.4, 0),
            ('MAT', 'SOL_PRATA', 3, 0),
            ('MAT', 'SOL_FLUXO', 0.3, 0),
            ('MO', 'MO_TEC', 5, 0.3),
            ('MO', 'MO_AJU', 5, 0.3),
            ('FER', 'FER_VACUO', 1, 0),
            ('FER', 'FER_MANIF', 1, 0),
            ('FER', 'FER_SOLDA', 1, 0),
            ('FER', 'FER_MANUAL', 5, 0),
            ('FER', 'FER_PERF', 0.75, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_PT_48K',
        'descricao': 'Instalação Split Piso-Teto 48.000 BTUs',
        'desc_pre': 'Instalação Split Piso-Teto 48.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_38_FLEX', 0, 1.1),
            ('MAT', 'TUB_58_FLEX', 0, 1.1),
            ('MAT', 'ISO_38_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_58_ELA_E19', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.4, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'SUP_MF_600', 1, 0),
            ('MAT', 'SUP_PARF_150', 4, 0),
            ('MAT', 'DRN_CRIS_100', 2, 0),
            ('MAT', 'ACA_ESPUMA', 0.5, 0),
            ('MAT', 'ACA_FITA_ISO', 0.5, 0),
            ('MAT', 'SOL_PRATA', 4, 0),
            ('MAT', 'SOL_FLUXO', 0.4, 0),
            ('MO', 'MO_TEC', 6, 0.35),
            ('MO', 'MO_AJU', 6, 0.35),
            ('FER', 'FER_VACUO', 1.25, 0),
            ('FER', 'FER_MANIF', 1.25, 0),
            ('FER', 'FER_SOLDA', 1.25, 0),
            ('FER', 'FER_MANUAL', 6, 0),
            ('FER', 'FER_PERF', 0.75, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_PT_60K',
        'descricao': 'Instalação Split Piso-Teto 60.000 BTUs',
        'desc_pre': 'Instalação Split Piso-Teto 60.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_38_FLEX', 0, 1.1),
            ('MAT', 'TUB_34_FLEX', 0, 1.1),
            ('MAT', 'ISO_38_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_34_ELA_E19', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.5, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'SUP_MF_600', 1, 0),
            ('MAT', 'SUP_PARF_150', 4, 0),
            ('MAT', 'DRN_CRIS_100', 3, 0),
            ('MAT', 'ACA_ESPUMA', 0.6, 0),
            ('MAT', 'ACA_FITA_ISO', 0.6, 0),
            ('MAT', 'SOL_PRATA', 4, 0),
            ('MAT', 'SOL_FLUXO', 0.4, 0),
            ('MO', 'MO_TEC', 7, 0.4),
            ('MO', 'MO_AJU', 7, 0.4),
            ('FER', 'FER_VACUO', 1.5, 0),
            ('FER', 'FER_MANIF', 1.5, 0),
            ('FER', 'FER_SOLDA', 1.5, 0),
            ('FER', 'FER_MANUAL', 7, 0),
            ('FER', 'FER_PERF', 1, 0),
        ]
    },
    # ========== INSTALAÇÕES CASSETE 1 VIA ==========
    {
        'codigo': 'COMP_INST_CS1_18K',
        'descricao': 'Instalação Split Cassete 1 Via 18.000 BTUs',
        'desc_pre': 'Instalação Split Cassete 1 Via 18.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_14_FLEX', 0, 1.1),
            ('MAT', 'TUB_12_FLEX', 0, 1.1),
            ('MAT', 'ISO_14_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_12_ELA_E13', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.25, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'CS_PAINEL_120', 1, 0),
            ('MAT', 'CS_SUSP_VARET', 1, 0),
            ('MAT', 'CS_DRENO_BOMB', 1, 0),
            ('MAT', 'DRN_CRIS_34', 3, 0),
            ('MAT', 'ACA_ESPUMA', 0.3, 0),
            ('MAT', 'ACA_FITA_ISO', 0.3, 0),
            ('MAT', 'SOL_PRATA', 2, 0),
            ('MAT', 'SOL_FLUXO', 0.2, 0),
            ('MO', 'MO_TEC', 4, 0.2),
            ('MO', 'MO_AJU', 4, 0.2),
            ('FER', 'FER_VACUO', 0.75, 0),
            ('FER', 'FER_MANIF', 0.75, 0),
            ('FER', 'FER_SOLDA', 0.75, 0),
            ('FER', 'FER_MANUAL', 4, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_CS1_24K',
        'descricao': 'Instalação Split Cassete 1 Via 24.000 BTUs',
        'desc_pre': 'Instalação Split Cassete 1 Via 24.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_14_FLEX', 0, 1.1),
            ('MAT', 'TUB_12_FLEX', 0, 1.1),
            ('MAT', 'ISO_14_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_12_ELA_E13', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.3, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'CS_PAINEL_120', 1, 0),
            ('MAT', 'CS_SUSP_VARET', 1, 0),
            ('MAT', 'CS_DRENO_BOMB', 1, 0),
            ('MAT', 'DRN_CRIS_34', 3, 0),
            ('MAT', 'ACA_ESPUMA', 0.3, 0),
            ('MAT', 'ACA_FITA_ISO', 0.3, 0),
            ('MAT', 'SOL_PRATA', 3, 0),
            ('MAT', 'SOL_FLUXO', 0.3, 0),
            ('MO', 'MO_TEC', 4.5, 0.25),
            ('MO', 'MO_AJU', 4.5, 0.25),
            ('FER', 'FER_VACUO', 0.75, 0),
            ('FER', 'FER_MANIF', 0.75, 0),
            ('FER', 'FER_SOLDA', 0.75, 0),
            ('FER', 'FER_MANUAL', 4.5, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_CS1_36K',
        'descricao': 'Instalação Split Cassete 1 Via 36.000 BTUs',
        'desc_pre': 'Instalação Split Cassete 1 Via 36.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_38_FLEX', 0, 1.1),
            ('MAT', 'TUB_58_FLEX', 0, 1.1),
            ('MAT', 'ISO_38_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_58_ELA_E19', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.35, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'CS_PAINEL_120', 1, 0),
            ('MAT', 'CS_SUSP_VARET', 1, 0),
            ('MAT', 'CS_DRENO_BOMB', 1, 0),
            ('MAT', 'DRN_CRIS_100', 3, 0),
            ('MAT', 'ACA_ESPUMA', 0.4, 0),
            ('MAT', 'ACA_FITA_ISO', 0.4, 0),
            ('MAT', 'SOL_PRATA', 3, 0),
            ('MAT', 'SOL_FLUXO', 0.3, 0),
            ('MO', 'MO_TEC', 5, 0.3),
            ('MO', 'MO_AJU', 5, 0.3),
            ('FER', 'FER_VACUO', 1, 0),
            ('FER', 'FER_MANIF', 1, 0),
            ('FER', 'FER_SOLDA', 1, 0),
            ('FER', 'FER_MANUAL', 5, 0),
        ]
    },
    # ========== INSTALAÇÕES BUILT-IN (DUTADO) ==========
    {
        'codigo': 'COMP_INST_BI_18K',
        'descricao': 'Instalação Split Built-in 18.000 BTUs',
        'desc_pre': 'Instalação Split Built-in 18.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_14_FLEX', 0, 1.1),
            ('MAT', 'TUB_12_FLEX', 0, 1.1),
            ('MAT', 'ISO_14_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_12_ELA_E13', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.25, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'BI_PLENUM', 1, 0),
            ('MAT', 'BI_DUTO_FLEX_200', 5, 0),
            ('MAT', 'BI_GRELHA_INS_200', 2, 0),
            ('MAT', 'BI_GRELHA_RET_300', 1, 0),
            ('MAT', 'BI_FITA_ALUM', 0.1, 0),
            ('MAT', 'DRN_CRIS_34', 2, 0),
            ('MAT', 'ACA_ESPUMA', 0.4, 0),
            ('MAT', 'SOL_PRATA', 2, 0),
            ('MAT', 'SOL_FLUXO', 0.2, 0),
            ('MO', 'MO_TEC', 5, 0.2),
            ('MO', 'MO_AJU', 5, 0.2),
            ('FER', 'FER_VACUO', 0.75, 0),
            ('FER', 'FER_MANIF', 0.75, 0),
            ('FER', 'FER_SOLDA', 0.75, 0),
            ('FER', 'FER_MANUAL', 5, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_BI_24K',
        'descricao': 'Instalação Split Built-in 24.000 BTUs',
        'desc_pre': 'Instalação Split Built-in 24.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_14_FLEX', 0, 1.1),
            ('MAT', 'TUB_12_FLEX', 0, 1.1),
            ('MAT', 'ISO_14_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_12_ELA_E13', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.3, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'BI_PLENUM', 1, 0),
            ('MAT', 'BI_DUTO_FLEX_200', 6, 0),
            ('MAT', 'BI_GRELHA_INS_200', 2, 0),
            ('MAT', 'BI_GRELHA_RET_300', 1, 0),
            ('MAT', 'BI_REGIST_200', 2, 0),
            ('MAT', 'BI_FITA_ALUM', 0.15, 0),
            ('MAT', 'DRN_CRIS_34', 2, 0),
            ('MAT', 'ACA_ESPUMA', 0.4, 0),
            ('MAT', 'SOL_PRATA', 3, 0),
            ('MAT', 'SOL_FLUXO', 0.3, 0),
            ('MO', 'MO_TEC', 6, 0.25),
            ('MO', 'MO_AJU', 6, 0.25),
            ('FER', 'FER_VACUO', 0.75, 0),
            ('FER', 'FER_MANIF', 0.75, 0),
            ('FER', 'FER_SOLDA', 0.75, 0),
            ('FER', 'FER_MANUAL', 6, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_BI_36K',
        'descricao': 'Instalação Split Built-in 36.000 BTUs',
        'desc_pre': 'Instalação Split Built-in 36.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_38_FLEX', 0, 1.1),
            ('MAT', 'TUB_58_FLEX', 0, 1.1),
            ('MAT', 'ISO_38_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_58_ELA_E19', 0, 1.1),
            ('MAT', 'ACA_FITA_TER', 0.35, 0),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'BI_PLENUM', 1, 0),
            ('MAT', 'BI_DUTO_FLEX_250', 8, 0),
            ('MAT', 'BI_GRELHA_INS_300', 3, 0),
            ('MAT', 'BI_GRELHA_RET_300', 1, 0),
            ('MAT', 'BI_REGIST_200', 3, 0),
            ('MAT', 'BI_FITA_ALUM', 0.2, 0),
            ('MAT', 'DRN_CRIS_100', 2, 0),
            ('MAT', 'ACA_ESPUMA', 0.5, 0),
            ('MAT', 'SOL_PRATA', 3, 0),
            ('MAT', 'SOL_FLUXO', 0.3, 0),
            ('MO', 'MO_TEC', 7, 0.3),
            ('MO', 'MO_AJU', 7, 0.3),
            ('FER', 'FER_VACUO', 1, 0),
            ('FER', 'FER_MANIF', 1, 0),
            ('FER', 'FER_SOLDA', 1, 0),
            ('FER', 'FER_MANUAL', 7, 0),
        ]
    },
    # ========== MANUTENÇÕES PREVENTIVAS ==========
    {
        'codigo': 'COMP_MANUT_PREV_P',
        'descricao': 'Manutenção preventiva 9-12K BTUs',
        'itens': [
            ('MAT', 'PECA_FILT_AR', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.1, 0),
            ('MAT', 'GAS_N2', 0.5, 0),
            ('MO', 'MO_TEC', 1.5, 0),
            ('FER', 'FER_MANIF', 0.25, 0),
            ('FER', 'FER_MULT', 0.25, 0),
            ('FER', 'FER_MANUAL', 1.5, 0),
        ]
    },
    {
        'codigo': 'COMP_MANUT_PREV_M',
        'descricao': 'Manutenção preventiva 18-30K BTUs',
        'itens': [
            ('MAT', 'PECA_FILT_AR', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.15, 0),
            ('MAT', 'GAS_N2', 0.5, 0),
            ('MO', 'MO_TEC', 2, 0),
            ('FER', 'FER_MANIF', 0.5, 0),
            ('FER', 'FER_MULT', 0.5, 0),
            ('FER', 'FER_MANUAL', 2, 0),
        ]
    },
    {
        'codigo': 'COMP_MANUT_PREV_G',
        'descricao': 'Manutenção preventiva 36-60K BTUs',
        'itens': [
            ('MAT', 'PECA_FILT_AR', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.2, 0),
            ('MAT', 'GAS_N2', 1, 0),
            ('MO', 'MO_TEC', 2.5, 0),
            ('MO', 'MO_AJU', 0.5, 0),
            ('FER', 'FER_MANIF', 0.75, 0),
            ('FER', 'FER_MULT', 0.75, 0),
            ('FER', 'FER_MANUAL', 2.5, 0),
        ]
    },
    # ========== LIMPEZA PROFUNDA ==========
    {
        'codigo': 'COMP_LIMP_PROF_HW',
        'descricao': 'Limpeza profunda Hi-Wall (com desmontagem)',
        'itens': [
            ('MAT', 'PECA_FILT_AR', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.1, 0),
            ('MO', 'MO_TEC', 2.5, 0),
            ('MO', 'MO_AJU', 1, 0),
            ('FER', 'FER_MANUAL', 2.5, 0),
        ]
    },
    {
        'codigo': 'COMP_LIMP_PROF_CS',
        'descricao': 'Limpeza profunda Cassete (com desmontagem)',
        'itens': [
            ('MAT', 'PECA_FILT_AR', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.15, 0),
            ('MO', 'MO_TEC', 3, 0),
            ('MO', 'MO_AJU', 1.5, 0),
            ('FER', 'FER_MANUAL', 3, 0),
        ]
    },
    {
        'codigo': 'COMP_LIMP_PROF_PT',
        'descricao': 'Limpeza profunda Piso-Teto',
        'itens': [
            ('MAT', 'PECA_FILT_AR', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.15, 0),
            ('MO', 'MO_TEC', 2.5, 0),
            ('MO', 'MO_AJU', 1, 0),
            ('FER', 'FER_MANUAL', 2.5, 0),
        ]
    },
    # ========== TROCA DE COMPRESSOR ==========
    {
        'codigo': 'COMP_TROCA_COMP_9K',
        'descricao': 'Troca de compressor 9.000 BTUs',
        'itens': [
            ('MAT', 'PECA_COMP_9K', 1, 0),
            ('MAT', 'PECA_FILT_SEC', 1, 0),
            ('MAT', 'GAS_R410A', 0.8, 0),
            ('MAT', 'SOL_PRATA', 4, 0),
            ('MAT', 'SOL_FLUXO', 0.3, 0),
            ('MAT', 'GAS_N2', 1, 0),
            ('MO', 'MO_TEC', 4, 0),
            ('MO', 'MO_AJU', 2, 0),
            ('FER', 'FER_VACUO', 1, 0),
            ('FER', 'FER_MANIF', 1, 0),
            ('FER', 'FER_SOLDA', 1.5, 0),
            ('FER', 'FER_BAL', 0.5, 0),
            ('FER', 'FER_MANUAL', 4, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_COMP_12K',
        'descricao': 'Troca de compressor 12.000 BTUs',
        'itens': [
            ('MAT', 'PECA_COMP_12K', 1, 0),
            ('MAT', 'PECA_FILT_SEC', 1, 0),
            ('MAT', 'GAS_R410A', 1, 0),
            ('MAT', 'SOL_PRATA', 4, 0),
            ('MAT', 'SOL_FLUXO', 0.3, 0),
            ('MAT', 'GAS_N2', 1, 0),
            ('MO', 'MO_TEC', 4.5, 0),
            ('MO', 'MO_AJU', 2, 0),
            ('FER', 'FER_VACUO', 1, 0),
            ('FER', 'FER_MANIF', 1, 0),
            ('FER', 'FER_SOLDA', 1.5, 0),
            ('FER', 'FER_BAL', 0.5, 0),
            ('FER', 'FER_MANUAL', 4.5, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_COMP_18K',
        'descricao': 'Troca de compressor 18.000 BTUs',
        'itens': [
            ('MAT', 'PECA_COMP_18K', 1, 0),
            ('MAT', 'PECA_FILT_SEC', 1, 0),
            ('MAT', 'GAS_R410A', 1.2, 0),
            ('MAT', 'SOL_PRATA', 4, 0),
            ('MAT', 'SOL_FLUXO', 0.3, 0),
            ('MAT', 'GAS_N2', 1, 0),
            ('MO', 'MO_TEC', 5, 0),
            ('MO', 'MO_AJU', 2.5, 0),
            ('FER', 'FER_VACUO', 1.25, 0),
            ('FER', 'FER_MANIF', 1.25, 0),
            ('FER', 'FER_SOLDA', 2, 0),
            ('FER', 'FER_BAL', 0.5, 0),
            ('FER', 'FER_MANUAL', 5, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_COMP_24K',
        'descricao': 'Troca de compressor 24.000 BTUs',
        'itens': [
            ('MAT', 'PECA_COMP_24K', 1, 0),
            ('MAT', 'PECA_FILT_SEC', 1, 0),
            ('MAT', 'GAS_R410A', 1.5, 0),
            ('MAT', 'SOL_PRATA', 5, 0),
            ('MAT', 'SOL_FLUXO', 0.4, 0),
            ('MAT', 'GAS_N2', 1, 0),
            ('MO', 'MO_TEC', 5.5, 0),
            ('MO', 'MO_AJU', 3, 0),
            ('FER', 'FER_VACUO', 1.5, 0),
            ('FER', 'FER_MANIF', 1.5, 0),
            ('FER', 'FER_SOLDA', 2, 0),
            ('FER', 'FER_BAL', 0.75, 0),
            ('FER', 'FER_MANUAL', 5.5, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_COMP_36K',
        'descricao': 'Troca de compressor 36.000 BTUs',
        'itens': [
            ('MAT', 'PECA_COMP_36K', 1, 0),
            ('MAT', 'PECA_FILT_SEC', 1, 0),
            ('MAT', 'GAS_R410A', 2, 0),
            ('MAT', 'SOL_PRATA', 6, 0),
            ('MAT', 'SOL_FLUXO', 0.5, 0),
            ('MAT', 'GAS_N2', 1.5, 0),
            ('MO', 'MO_TEC', 6, 0),
            ('MO', 'MO_AJU', 3, 0),
            ('FER', 'FER_VACUO', 2, 0),
            ('FER', 'FER_MANIF', 2, 0),
            ('FER', 'FER_SOLDA', 2.5, 0),
            ('FER', 'FER_BAL', 1, 0),
            ('FER', 'FER_MANUAL', 6, 0),
        ]
    },
    # ========== TROCA DE PLACAS ==========
    {
        'codigo': 'COMP_TROCA_PLC_IND',
        'descricao': 'Troca placa eletrônica indoor',
        'itens': [
            ('MAT', 'PECA_PLC_IND_9_18', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.1, 0),
            ('MO', 'MO_TEC', 1.5, 0),
            ('FER', 'FER_MULT', 0.5, 0),
            ('FER', 'FER_MANUAL', 1.5, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_PLC_OUT',
        'descricao': 'Troca placa eletrônica outdoor',
        'itens': [
            ('MAT', 'PECA_PLC_OUT_9_18', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.1, 0),
            ('MO', 'MO_TEC', 2, 0),
            ('FER', 'FER_MULT', 0.75, 0),
            ('FER', 'FER_MANUAL', 2, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_PLC_INV',
        'descricao': 'Troca placa inverter',
        'itens': [
            ('MAT', 'PECA_PLC_INV', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.1, 0),
            ('MO', 'MO_TEC', 2.5, 0),
            ('FER', 'FER_MULT', 1, 0),
            ('FER', 'FER_MANUAL', 2.5, 0),
        ]
    },
    # ========== TROCA DE MOTORES ==========
    {
        'codigo': 'COMP_TROCA_MOT_EVAP',
        'descricao': 'Troca motor ventilador evaporadora',
        'itens': [
            ('MAT', 'PECA_MOT_EVAP_M', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.1, 0),
            ('MO', 'MO_TEC', 2, 0),
            ('FER', 'FER_MULT', 0.5, 0),
            ('FER', 'FER_MANUAL', 2, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_MOT_COND',
        'descricao': 'Troca motor ventilador condensadora',
        'itens': [
            ('MAT', 'PECA_MOT_COND_M', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.1, 0),
            ('MO', 'MO_TEC', 2.5, 0),
            ('FER', 'FER_MULT', 0.5, 0),
            ('FER', 'FER_MANUAL', 2.5, 0),
        ]
    },
    # ========== TROCA DE SENSORES E VÁLVULAS ==========
    {
        'codigo': 'COMP_TROCA_SENSOR',
        'descricao': 'Troca sensor (temperatura/degelo/pressão)',
        'itens': [
            ('MAT', 'PECA_SENS_TEMP_AMB', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.05, 0),
            ('MO', 'MO_TEC', 1, 0),
            ('FER', 'FER_MULT', 0.25, 0),
            ('FER', 'FER_MANUAL', 1, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_VALV_EXP',
        'descricao': 'Troca válvula expansão eletrônica',
        'itens': [
            ('MAT', 'PECA_VALV_EXP', 1, 0),
            ('MAT', 'GAS_R410A', 0.3, 0),
            ('MAT', 'ACA_FITA_ISO', 0.1, 0),
            ('MO', 'MO_TEC', 2.5, 0),
            ('FER', 'FER_MANIF', 0.5, 0),
            ('FER', 'FER_VACUO', 0.5, 0),
            ('FER', 'FER_MANUAL', 2.5, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_VALV_4VIAS',
        'descricao': 'Troca válvula 4 vias (reversão)',
        'itens': [
            ('MAT', 'PECA_VALV_4VIAS', 1, 0),
            ('MAT', 'GAS_R410A', 0.5, 0),
            ('MAT', 'SOL_PRATA', 3, 0),
            ('MAT', 'SOL_FLUXO', 0.2, 0),
            ('MO', 'MO_TEC', 3, 0),
            ('MO', 'MO_AJU', 1, 0),
            ('FER', 'FER_MANIF', 0.75, 0),
            ('FER', 'FER_VACUO', 0.75, 0),
            ('FER', 'FER_SOLDA', 1, 0),
            ('FER', 'FER_MANUAL', 3, 0),
        ]
    },
    # ========== TROCA DE CAPACITORES ==========
    {
        'codigo': 'COMP_TROCA_CAPAC',
        'descricao': 'Troca capacitor (partida/permanente)',
        'itens': [
            ('MAT', 'PECA_CAP_PERM_M', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.05, 0),
            ('MO', 'MO_TEC', 0.75, 0),
            ('FER', 'FER_MULT', 0.25, 0),
            ('FER', 'FER_MANUAL', 0.75, 0),
        ]
    },
    # ========== DESINSTALAÇÃO E REINSTALAÇÃO ==========
    {
        'codigo': 'COMP_REINST_HW',
        'descricao': 'Reinstalação Split Hi-Wall (mesmo local)',
        'itens': [
            ('MAT', 'SOL_PRATA', 2, 0),
            ('MAT', 'SOL_FLUXO', 0.2, 0),
            ('MAT', 'ACA_FITA_ISO', 0.2, 0),
            ('MO', 'MO_TEC', 3, 0),
            ('MO', 'MO_AJU', 3, 0),
            ('FER', 'FER_VACUO', 0.5, 0),
            ('FER', 'FER_MANIF', 0.5, 0),
            ('FER', 'FER_SOLDA', 0.5, 0),
            ('FER', 'FER_MANUAL', 3, 0),
        ]
    },
    {
        'codigo': 'COMP_REINST_CS',
        'descricao': 'Reinstalação Split Cassete (mesmo local)',
        'itens': [
            ('MAT', 'SOL_PRATA', 2, 0),
            ('MAT', 'SOL_FLUXO', 0.2, 0),
            ('MAT', 'ACA_FITA_ISO', 0.2, 0),
            ('MAT', 'CS_SUSP_VARET', 1, 0),
            ('MO', 'MO_TEC', 4, 0),
            ('MO', 'MO_AJU', 4, 0),
            ('FER', 'FER_VACUO', 0.75, 0),
            ('FER', 'FER_MANIF', 0.75, 0),
            ('FER', 'FER_SOLDA', 0.75, 0),
            ('FER', 'FER_MANUAL', 4, 0),
        ]
    },
    {
        'codigo': 'COMP_REINST_PT',
        'descricao': 'Reinstalação Split Piso-Teto (mesmo local)',
        'itens': [
            ('MAT', 'SOL_PRATA', 2, 0),
            ('MAT', 'SOL_FLUXO', 0.2, 0),
            ('MAT', 'ACA_FITA_ISO', 0.2, 0),
            ('MAT', 'SUP_PARF_150', 4, 0),
            ('MO', 'MO_TEC', 3.5, 0),
            ('MO', 'MO_AJU', 3.5, 0),
            ('FER', 'FER_VACUO', 0.75, 0),
            ('FER', 'FER_MANIF', 0.75, 0),
            ('FER', 'FER_SOLDA', 0.75, 0),
            ('FER', 'FER_MANUAL', 3.5, 0),
            ('FER', 'FER_PERF', 0.5, 0),
        ]
    },
    # ========== SERVIÇOS COMPLEMENTARES ==========
    {
        'codigo': 'COMP_DRENAGEM_GRAV',
        'descricao': 'Sistema dreno por gravidade (PVC rígido)',
        'desc_pre': 'Sistema dreno por gravidade com ',
        'desc_pos': ' de tubulação PVC',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'DRN_PVC_25', 0, 1.1),
            ('MAT', 'DRN_CURV_25', 2, 0),
            ('MAT', 'DRN_LUVA_25', 0, 0.5),
            ('MAT', 'DRN_COLA', 0.3, 0),
            ('MAT', 'DRN_SIFAO', 1, 0),
            ('MO', 'MO_TEC', 1.5, 0.2),
            ('FER', 'FER_MANUAL', 1.5, 0.2),
        ]
    },
    {
        'codigo': 'COMP_PROT_COND',
        'descricao': 'Proteção condensadora (grade/tela)',
        'itens': [
            ('MAT', 'SUP_MF_400', 1, 0),
            ('MAT', 'SUP_PARF_100', 4, 0),
            ('MO', 'MO_TEC', 1.5, 0),
            ('MO', 'MO_AJU', 1.5, 0),
            ('FER', 'FER_PERF', 0.5, 0),
            ('FER', 'FER_MANUAL', 1.5, 0),
        ]
    },
    {
        'codigo': 'COMP_TESTE_ESTANQ',
        'descricao': 'Teste estanqueidade com nitrogênio',
        'itens': [
            ('MAT', 'GAS_N2', 2, 0),
            ('MO', 'MO_TEC', 1, 0),
            ('FER', 'FER_MANIF', 0.5, 0),
            ('FER', 'FER_ESTANQ', 0.5, 0),
        ]
    },
    {
        'codigo': 'COMP_RECUP_GAS',
        'descricao': 'Recuperação gás refrigerante',
        'itens': [
            ('MO', 'MO_TEC', 1.5, 0),
            ('FER', 'FER_MANIF', 0.75, 0),
            ('FER', 'FER_VACUO', 0.75, 0),
        ]
    },
    {
        'codigo': 'COMP_VISTORIA',
        'descricao': 'Vistoria técnica e diagnóstico',
        'itens': [
            ('MO', 'MO_TEC', 2, 0),
            ('MO', 'MO_DESL_20', 1, 0),
            ('FER', 'FER_MULT', 0.5, 0),
            ('FER', 'FER_MANIF', 0.5, 0),
            ('FER', 'FER_MANUAL', 1, 0),
        ]
    },

    # ========== SPRINT 2 - CORRETIVAS E VISITAS ==========
    {
        'codigo': 'COMP_CORR_VAZAMENTO',
        'descricao': 'Correção de vazamento em linha frigorígena',
        'itens': [
            ('MAT', 'SOL_PRATA', 3, 0),
            ('MAT', 'SOL_FLUXO', 0.2, 0),
            ('MAT', 'GAS_N2', 1, 0),
            ('MO', 'MO_TEC', 2.5, 0),
            ('MO', 'MO_AJU', 1, 0),
            ('FER', 'FER_MANIF', 0.75, 0),
            ('FER', 'FER_SOLDA', 1, 0),
            ('FER', 'FER_ESTANQ', 0.5, 0),
        ]
    },
    {
        'codigo': 'COMP_REPARO_LINHA',
        'descricao': 'Reparo de linha frigorígena com troca de trecho',
        'desc_pre': 'Reparo de linha frigorígena com troca de ',
        'desc_pos': ' de tubulação',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_38_FLEX', 0, 1.1),
            ('MAT', 'ISO_38_ELA_E13', 0, 1.1),
            ('MAT', 'SOL_PRATA', 2, 0.5),
            ('MAT', 'SOL_FLUXO', 0.2, 0.05),
            ('MAT', 'ACA_FITA_TER', 0.1, 0.2),
            ('MO', 'MO_TEC', 1.5, 0.35),
            ('MO', 'MO_AJU', 0.75, 0.2),
            ('FER', 'FER_SOLDA', 0.75, 0.2),
            ('FER', 'FER_MANIF', 0.5, 0.1),
        ]
    },
    {
        'codigo': 'COMP_LIMP_QUIM_EVAP',
        'descricao': 'Limpeza química de serpentina evaporadora',
        'itens': [
            ('MAT', 'PECA_FILT_AR', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.1, 0),
            ('MO', 'MO_TEC', 2, 0),
            ('MO', 'MO_AJU', 0.75, 0),
            ('FER', 'FER_MANUAL', 2, 0),
        ]
    },
    {
        'codigo': 'COMP_LIMP_QUIM_COND',
        'descricao': 'Limpeza química de serpentina condensadora',
        'itens': [
            ('MAT', 'ACA_FITA_ISO', 0.1, 0),
            ('MO', 'MO_TEC', 2.25, 0),
            ('MO', 'MO_AJU', 1, 0),
            ('FER', 'FER_MANUAL', 2.25, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_PLC_FAIXA_P',
        'descricao': 'Troca placa eletrônica (faixa 9-18K)',
        'itens': [
            ('MAT', 'PECA_PLC_IND_9_18', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.1, 0),
            ('MO', 'MO_TEC', 1.5, 0),
            ('FER', 'FER_MULT', 0.5, 0),
            ('FER', 'FER_MANUAL', 1.5, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_PLC_FAIXA_M',
        'descricao': 'Troca placa eletrônica (faixa 24-36K)',
        'itens': [
            ('MAT', 'PECA_PLC_IND_24_30', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.1, 0),
            ('MO', 'MO_TEC', 2, 0),
            ('FER', 'FER_MULT', 0.75, 0),
            ('FER', 'FER_MANUAL', 2, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_PLC_FAIXA_G',
        'descricao': 'Troca placa eletrônica (faixa 48-60K)',
        'itens': [
            ('MAT', 'PECA_PLC_IND_36_60', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.1, 0),
            ('MO', 'MO_TEC', 2.5, 0),
            ('FER', 'FER_MULT', 1, 0),
            ('FER', 'FER_MANUAL', 2.5, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_MOT_FAIXA_P',
        'descricao': 'Troca motor ventilador (faixa P 9-12K)',
        'itens': [
            ('MAT', 'PECA_MOT_EVAP_P', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.1, 0),
            ('MO', 'MO_TEC', 1.75, 0),
            ('FER', 'FER_MULT', 0.5, 0),
            ('FER', 'FER_MANUAL', 1.75, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_MOT_FAIXA_M',
        'descricao': 'Troca motor ventilador (faixa M 18-24K)',
        'itens': [
            ('MAT', 'PECA_MOT_EVAP_M', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.1, 0),
            ('MO', 'MO_TEC', 2, 0),
            ('FER', 'FER_MULT', 0.5, 0),
            ('FER', 'FER_MANUAL', 2, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_MOT_FAIXA_G',
        'descricao': 'Troca motor ventilador (faixa G 30-60K)',
        'itens': [
            ('MAT', 'PECA_MOT_EVAP_G', 1, 0),
            ('MAT', 'ACA_FITA_ISO', 0.1, 0),
            ('MO', 'MO_TEC', 2.5, 0),
            ('FER', 'FER_MULT', 0.75, 0),
            ('FER', 'FER_MANUAL', 2.5, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_SENSOR_AMB',
        'descricao': 'Troca sensor de temperatura ambiente',
        'itens': [
            ('MAT', 'PECA_SENS_TEMP_AMB', 1, 0),
            ('MO', 'MO_TEC', 0.75, 0),
            ('FER', 'FER_MULT', 0.25, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_SENSOR_EVAP',
        'descricao': 'Troca sensor de temperatura evaporadora',
        'itens': [
            ('MAT', 'PECA_SENS_TEMP_EVAP', 1, 0),
            ('MO', 'MO_TEC', 0.75, 0),
            ('FER', 'FER_MULT', 0.25, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_SENSOR_COND',
        'descricao': 'Troca sensor de temperatura condensadora',
        'itens': [
            ('MAT', 'PECA_SENS_TEMP_COND', 1, 0),
            ('MO', 'MO_TEC', 0.75, 0),
            ('FER', 'FER_MULT', 0.25, 0),
        ]
    },
    {
        'codigo': 'COMP_TROCA_SENSOR_PRES',
        'descricao': 'Troca sensor de pressão (alta/baixa)',
        'itens': [
            ('MAT', 'PECA_SENS_PRES', 1, 0),
            ('MO', 'MO_TEC', 1, 0),
            ('FER', 'FER_MULT', 0.3, 0),
        ]
    },
    {
        'codigo': 'COMP_VISITA_SIMPLES',
        'descricao': 'Visita técnica sem execução',
        'itens': [
            ('MO', 'MO_TEC', 1.5, 0),
            ('MO', 'MO_DESL_20', 1, 0),
            ('FER', 'FER_MULT', 0.25, 0),
        ]
    },
    {
        'codigo': 'COMP_VISITA_LAUDO',
        'descricao': 'Visita técnica com laudo',
        'itens': [
            ('MO', 'MO_TEC', 2.5, 0),
            ('MO', 'MO_DESL_20', 1, 0),
            ('FER', 'FER_MULT', 0.5, 0),
            ('FER', 'FER_MANUAL', 0.5, 0),
        ]
    },
    {
        'codigo': 'COMP_VISITA_DESL_EST',
        'descricao': 'Visita técnica com deslocamento estendido',
        'itens': [
            ('MO', 'MO_TEC', 2, 0),
            ('MO', 'MO_DESL_50', 1, 0),
            ('FER', 'FER_MULT', 0.5, 0),
        ]
    },


    # ========== SPRINT 3 - CASOS ESPECIAIS ==========
    {
        'codigo': 'COMP_INST_FACH_RAPEL',
        'descricao': 'Instalação em fachada com rapel/plataforma',
        'itens': [
            ('MAT', 'SUP_MF_600', 1, 0),
            ('MAT', 'SUP_PARF_150', 4, 0),
            ('MAT', 'CAB_COM', 5, 0),
            ('MAT', 'DRN_CRIS_34', 5, 0),
            ('MAT', 'ACA_FITA_AUT', 0.2, 0),
            ('MO', 'MO_TEC', 4, 0),
            ('MO', 'MO_AJU', 4, 0),
            ('MO', 'MO_FAC', 4, 0),
            ('MO', 'MO_ALT', 4, 0),
            ('FER', 'FER_PERF', 1, 0),
            ('FER', 'FER_ESCADA', 2, 0),
            ('FER', 'FER_MANUAL', 3, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_CPD_CRITICO',
        'descricao': 'Instalação em ambiente crítico (CPD/laboratório)',
        'itens': [
            ('MAT', 'TUB_38_FLEX', 6, 0),
            ('MAT', 'TUB_58_FLEX', 6, 0),
            ('MAT', 'ISO_38_ELA_E13', 6, 0),
            ('MAT', 'ISO_58_ELA_E19', 6, 0),
            ('MAT', 'ACA_FITA_TER', 0.5, 0),
            ('MAT', 'ACA_FITA_AUT', 0.4, 0),
            ('MAT', 'CAB_COM', 5, 0),
            ('MAT', 'DRN_CRIS_34', 5, 0),
            ('MAT', 'GAS_N2', 1.5, 0),
            ('MO', 'MO_TEC', 6, 0),
            ('MO', 'MO_AJU', 3, 0),
            ('FER', 'FER_ESTANQ', 1, 0),
            ('FER', 'FER_MANIF', 1, 0),
            ('FER', 'FER_VACUO', 1, 0),
            ('FER', 'FER_MANUAL', 4, 0),
        ]
    },
    {
        'codigo': 'COMP_REINST_MUD_POS',
        'descricao': 'Reinstalação com mudança de posição (obra civil leve)',
        'desc_pre': 'Reinstalação com mudança de posição e ',
        'desc_pos': ' de ajuste em infraestrutura',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_38_FLEX', 0, 1.1),
            ('MAT', 'ISO_38_ELA_E13', 0, 1.1),
            ('MAT', 'SOL_PRATA', 2, 0.2),
            ('MAT', 'SOL_FLUXO', 0.2, 0.05),
            ('MAT', 'ACA_ESPUMA', 0.2, 0.05),
            ('MAT', 'ALV_ARG', 0.1, 0.2),
            ('MO', 'MO_TEC', 2.5, 0.25),
            ('MO', 'MO_AJU', 2.5, 0.25),
            ('MO', 'MO_PED', 0.5, 0.2),
            ('FER', 'FER_MANUAL', 2, 0.25),
            ('FER', 'FER_PERF', 0.5, 0.1),
        ]
    },
    {
        'codigo': 'COMP_INST_BI_48K',
        'descricao': 'Instalação Split Built-in 48.000 BTUs',
        'desc_pre': 'Instalação Split Built-in 48.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_38_FLEX', 0, 1.1),
            ('MAT', 'TUB_58_FLEX', 0, 1.1),
            ('MAT', 'ISO_38_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_58_ELA_E19', 0, 1.1),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'BI_PLENUM', 1, 0),
            ('MAT', 'BI_DUTO_FLEX_250', 10, 0),
            ('MAT', 'BI_GRELHA_INS_300', 4, 0),
            ('MAT', 'BI_GRELHA_RET_300', 2, 0),
            ('MAT', 'BI_REGIST_200', 4, 0),
            ('MAT', 'BI_FITA_ALUM', 0.25, 0),
            ('MAT', 'DRN_CRIS_100', 3, 0),
            ('MAT', 'SOL_PRATA', 3.5, 0),
            ('MAT', 'SOL_FLUXO', 0.35, 0),
            ('MO', 'MO_TEC', 8, 0.35),
            ('MO', 'MO_AJU', 8, 0.35),
            ('FER', 'FER_VACUO', 1.25, 0),
            ('FER', 'FER_MANIF', 1.25, 0),
            ('FER', 'FER_SOLDA', 1.25, 0),
            ('FER', 'FER_MANUAL', 8, 0),
        ]
    },
    {
        'codigo': 'COMP_INST_BI_60K',
        'descricao': 'Instalação Split Built-in 60.000 BTUs',
        'desc_pre': 'Instalação Split Built-in 60.000 BTUs com ',
        'desc_pos': ' de linha frigorígena',
        'unid_sing': 'metro',
        'unid_plur': 'metros',
        'itens': [
            ('MAT', 'TUB_38_FLEX', 0, 1.1),
            ('MAT', 'TUB_34_FLEX', 0, 1.1),
            ('MAT', 'ISO_38_ELA_E13', 0, 1.1),
            ('MAT', 'ISO_34_ELA_E19', 0, 1.1),
            ('MAT', 'CAB_COM', 0, 1.15),
            ('MAT', 'BI_PLENUM', 1, 0),
            ('MAT', 'BI_DUTO_FLEX_250', 12, 0),
            ('MAT', 'BI_GRELHA_INS_300', 5, 0),
            ('MAT', 'BI_GRELHA_RET_300', 2, 0),
            ('MAT', 'BI_REGIST_200', 5, 0),
            ('MAT', 'BI_FITA_ALUM', 0.3, 0),
            ('MAT', 'DRN_CRIS_100', 4, 0),
            ('MAT', 'SOL_PRATA', 4, 0),
            ('MAT', 'SOL_FLUXO', 0.4, 0),
            ('MO', 'MO_TEC', 9, 0.4),
            ('MO', 'MO_AJU', 9, 0.4),
            ('FER', 'FER_VACUO', 1.5, 0),
            ('FER', 'FER_MANIF', 1.5, 0),
            ('FER', 'FER_SOLDA', 1.5, 0),
            ('FER', 'FER_MANUAL', 9, 0),
        ]
    },

]
